version: '2'
services:
  mysql-gorm:
    image: mysql:5.7
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_USER: gorm
        MYSQL_PASSWORD: "gorm"
        MYSQL_DATABASE: first_go